### ISSUE TITLE
Error when unplug cable connecting PC and phone 

### ISSUE THREAD

**Issue by HLneoh** [viromedia/figment-ar#1]
Hi, I have downloaded the git repo and successfully build figment as an android app. It worked well when my phone was still connected to my PC. However, once I unplug the cable which is used to connect my phone with PC, the app returned me the error and warning as shown in below. Can anyone help pls?

![screenshot_20180821-190628_virosample-ar](https://user-images.githubusercontent.com/25906607/44621743-2dd5ea00-a8de-11e8-9c80-55f1d625e5e5.jpg)

![screenshot_20180825-231003_figment](https://user-images.githubusercontent.com/25906607/44621753-64ac0000-a8de-11e8-87d0-dbdf8296da54.jpg)

![screenshot_20180825-230936_figment](https://user-images.githubusercontent.com/25906607/44621758-90c78100-a8de-11e8-9e2c-217ed4f1cb0c.jpg)

**Comment by dam00n** [comment]
Did you follow these steps for Android Studio setup? -> https://docs.viromedia.com/docs/installing-viro-android

**Comment by HLneoh** [comment]
Thanks for the response, @dam00n.
Yes. I have followed all the steps for Android Studio setup.

**Comment by manbod** [comment]
Hi @HLneoh ,
What you are seeing is a react-native error. To connect your Android device to your PC over wifi please follow instructions from react-native docs here -> https://facebook.github.io/react-native/docs/running-on-device#method-2-connect-via-wi-fi . Copy pasting the exact instructions below

> Method 2: Connect via Wi-Fi
You can also connect to the development server over Wi-Fi. You'll first need to install the app on your device using a USB cable, but once that has been done you can debug wirelessly by following these instructions. You'll need your development machine's current IP address before proceeding.
>
> You can find the IP address in System Preferences → Network.
> 
> 1. Make sure your laptop and your phone are on the same Wi-Fi network.
> 2. Open your React Native app on your device.
> 3. You'll see a red screen with an error. This is OK. The following steps will fix that.
> 4. Open the in-app Developer menu.
> 5. Go to Dev Settings → Debug server host & port for device.
> 6. Type in your machine's IP address and the port of the local dev server (e.g. 10.0.1.1:8081).
> 7. Go back to the Developer menu and select Reload JS.

Later on, if you wish to connect your android device to the PC using a cable, then you'll have to follow instructions under **Method 1: Using adb reverse (recommended)** again.
