### ISSUE TITLE
getting Error when selecting Frames in Demo App in Android device and Crashed in iOS device

### ISSUE THREAD

**Issue by Sandeep155Vibhuti** [viromedia/figment-ar#19]
**invariant violation: Text string must be rendered within a <Text> component** 

react-native version: 0.59.9
Android Device Version: 11
iOS Device Version:  14.11

**Comment by Roopal-dev** [comment]
Follow this step and Issue gone

https://github.com/viromedia/figment-ar/pull/14/commits/1f3567423307d4642d9fbec798bb8f9321b7a1f2

**Comment by Sandeep155Vibhuti** [comment]
it works like charm thanks @Roopal-dev
