### ISSUE TITLE
Build error with react-native 0.55.4

### ISSUE THREAD

**Issue by pouraghajanOldAcc** [viromedia/figment-ar#2]
Hi
Let me explain first, debugging the app using a USB cable and a device works properly. The app gets installed on the device and it works.
But when I try to build the production APK version (Using this [instruction](https://docs.viromedia.com/docs/android-distribution)), there are couple of issues.
I'm using Windows 10, react-native 0.55.4 and JDK 1.8.
Firstly, in the build.gradle file the property used for accessing "node" is only Linux based.
it is "nodeExecutableAndArgs : ["/usr/local/bin/node"]" by default which results in an error during the build, pointing out that the requested path is not accessible (Which is odd if it would be on Windows OS ;) ). I have changed this value to "nodeExecutableAndArgs : ["node"]" and this issue has been resolved.

```
Starting process 'command 'cmd''. Working directory: E:\Workspaces\ARProjects\myarproject Command: cmd /c /usr/local/bin/node node_modules/react-native/local-cli/cli.js bundle --platform android --dev false --reset-cache --entry-file index.android.js --bundle-output E:\Workspaces\ARProjects\myarproject\android\app\build\intermediates\assets\gvr\release\index.android.bundle --assets-dest E:\Workspaces\ARProjects\myarproject\android\app\build\intermediates\res\merged\gvr\release
Successfully started process 'command 'cmd''
The system cannot find the path specified.
```
But my main problem is another error I've faced after rectifying the previous one. 

```
> Task :app:bundleGvrReleaseJsAndAssets
Loading dependency graph, done.

Cannot find entry file index.android.js in any of the roots: ["E:\\Workspaces\\ARProjects\\myarproject"]

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:bundleGvrReleaseJsAndAssets'.
> Process 'command 'cmd'' finished with non-zero exit value 1
```
It seems gradle is looking for some entry point JS file which it can't locate anywhere!!!
I have searched through different react-native forums and all of them only suggest to downgrade to an older version of react-native. But I don't believe that's a proper solution. We need to be able to build apps with the final version as well after all.
any thoughts??!!

**Comment by pouraghajanOldAcc** [comment]
To whom may it concerns.
The build.gradle file is the root cause of all build issues.
Just by changing the "nodeExecutablesAndArgs" parameter in build.gradle to the following value, the build process ran successfully.
`project.ext.react = [nodeExecutableAndArgs : ["node"], entryFile: 'index.js']`

The explanation behind this, is react-native-cli script (which is being used during the build process) looks for a default entry JS file (which represents your app's registering class) in the project root directory. if you don't provide the name of the registering class in build.gradle file, by default it searches for "index.android.js" for Android builds and "index.ios.js" for iOS builds. providing the entryFile property value can save you a lot of time building your react-native app (if you are using the latest version such as me).

**Comment by DianaCruz16** [comment]
Now i have this Error -.-
RN v0.59
React-viro v2.17

```
* Where:
Script 'C:\Users\smartjsp\Downloads\figment-ar\node_modules\react-native\react.gradle' line: 72

* What went wrong:
A problem occurred configuring project ':app'.
> Could not create task ':app:bundleGvrDebugJsAndAssets'.
   > cannot spread the type java.util.LinkedHashMap with value {nodeExecutableAndArgs=[node], entryFile=index.js}
```
